---
version: 1
story_title: "Que mon règne vienne"
resources:
    "gold":
        description: "Argent dans les coffres"
        format: "%s"
        display_name: "Richesse"
        default: 100
    "population":
        description: "La population de votre campement"
        format: "%s"
        display_name: "Population"
        default: 10
    "happiness":
        description: "Le bonheur de votre population"
        format: "%s"
        display_name: "Bonheur"
        default: 10
---

Envoyé par l'empereur pour civiliser et pacifier les bordures du royaume, votre petite expédition arrive en vue d'une clairière prometteuse...
