version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: mkdir /tmp/story
      - run: sudo apt install graphviz
      - run: npm run compile -- /tmp/story/story.json
      - run:
          name: Generate chart
          command: npm run chart -- /tmp/story/story.json /tmp/story/chart.json /tmp/story/chart.dot
          environment:
            # Generating the chart takes a lot of memory, make sure our script can access whatever it needs
            NODE_OPTIONS="--max-old-space-size=4096"
      - run: dot -Tsvg -o /tmp/story/chart.svg /tmp/story/chart.dot
      - store_artifacts:
          path: /tmp/story
          destination: story
